version: '3'

services:
  ddns:
    container_name: google-ddns
    restart: unless-stopped
    network_mode: "host"
    build: .
    volumes:
    - ./key:/app/key
    env_file:
      - proc.env
    # deploy:
    #   mode: global
